repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.0
    hooks:
      - id: cspell
        name: English-only language check
        args: [--no-progress, --no-summary, --show-context]

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        language: system
        entry: dotnet format CometBFT.Client.sln --verify-no-changes
        pass_filenames: false
      - id: detect-secrets
        name: detect secrets
        language: python
        entry: detect-secrets-hook
        args: ["--baseline", ".secrets.baseline"]
        pass_filenames: true
