services:
  dotnet:
    build:
      context: ../..
      dockerfile: scripts/docker/Dockerfile
    working_dir: /workspace
    environment:
      - NUGET_API_KEY
      - TENDERMINT_RPC_URL
      - TENDERMINT_WS_URL
      - TENDERMINT_GRPC_URL
